export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_PENDING = 'GET_PHOTOS';
export const OPEN_PHOTO_MODAL = 'OPEN_PHOTO_MODAL';
export const CLOSE_PHOTO_MODAL = 'CLOSE_PHOTO_MODAL';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SHOW_SEARCH_WORDS = 'SHOW_SEARCH_WORDS';
export const GET_PHOTOS_SEARCH = 'GET_PHOTOS_SEARCH';
export const GET_PHOTOS_SEARCH_PENDING = 'GET_PHOTOS_SEARCH_PENDING';